# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/minimal.nix")
    (modulesPath + "/installer/sd-card/sd-image-aarch64.nix")
  ];

  boot.kernelPackages = pkgs.linuxKernel.packages.linux_rpi3;
  boot.initrd.availableKernelModules = lib.mkOverride 0 [ ];
  boot.supportedFilesystems = lib.mkOverride 0 [ ];

  sdImage.compressImage = false;
}