# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#####################################
# seb NOTE: This build requires  3 partition-names:
# 'root' for the partition mounted on `/`.
# 'boot' for the partition mounted on `/boot`.
# 'data' for the partition mounted on `/data`.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "usbcore.autosuspend=-1" ]; # do not suspend USBs.
  boot.extraModprobeConfig = ''
    options usbcore autosuspend=-1
  ''; # do not suspend USBs.
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/root";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/EFI";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/data" = { # lvm disk array, setup using: https://askubuntu.com/a/7841/2355 and https://nixos.wiki/wiki/LVM
    device = "/dev/disk/by-partlabel/data";
    fsType = "ext4";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  my.hardware.networking = {
    enable = true;
    hostname = "helium";
    domain = "h.mijn.place";
    block-trackers = true;
    nameservers = [ "1.1.1.1" "1.0.0.1" ];
  };
}
