# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#####################################
# seb NOTE: This build requires  3 partition-names:
# 'root' for the partition mounted on `/`.
# 'boot' for the partition mounted on `/boot`.
# 'data' for the partition mounted on `/data`.
#
#
# seb TODO:
# Get a hold of that CPU fan.
# Suggestions:
# https://www.reddit.com/r/homelab/comments/10iuwro/slowing_down_fan_on_dell_optiplex_3080_linux/
# NixOS examples:
# https://github.com/ruhatch/nixos/tree/master
#
# Modules found:
# i8kutils - modern: https://github.com/Wer-Wolf/i8kutils/tree/master
# i8kutils - abandoned: https://github.com/vitorafsr/i8kutils/forks
# dell-fan-control: https://github.com/proneon267/Dell-Fan-Control
# 
# Actually working: change /sys/class/hwmon/hwmon1/pwm1 to contain "0"
# hwmon1 is named "dell_smm", as found in /sys/class/hwmon/hwmon1/name.

{ config, lib, pkgs, modulesPath, ... }: {
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "coretemp" "dell-smm-hwmon" ];
  boot.kernelModules = [
    "kvm-intel" #hardware virtualisation
    "dell-smm-hwmon" # dell smm fan control module
  ];
  boot.kernelParams = [ "usbcore.autosuspend=-1" ]; # do not suspend USBs.
  boot.extraModprobeConfig = ''
    options dell-smm-hwmon restricted=0 force=1
  ''; # do not suspend USBs, and load i8k
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-partlabel/root";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-partlabel/EFI";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/data" = { # lvm disk array, setup using: https://askubuntu.com/a/7841/2355 and https://nixos.wiki/wiki/LVM
    device = "/dev/disk/by-partlabel/data";
    fsType = "ext4";
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  my.hardware.networking = {
    enable = true;
    hostname = "helium";
    domain = "h.mijn.place";
    block-trackers = true;
    nameservers = [ "1.1.1.1" "1.0.0.1" ];
  };
}
