{ ... }: {
  imports = [
    ./adblock
    ./avahi
    ./audiobookshelf
    ./backup
    ./backup-server
    ./bind
    ./ddclient
    ./ddns-updater
    ./fail2ban
    ./flood
    ./forgejo
    ./gitea
    ./greetd
    ./grocy
    ./home-assistant
    ./immich
    ./jackett
    ./jellyfin
    ./kitchenowl
    ./matrix
    ./mailserver
    ./mealie
    ./meshcentral
    ./miniflux
    ./monitoring
    ./music-assistant
    ./navidrome
    ./nextcloud
    ./nfs
    ./nginx
    ./nzbhydra
    ./photoprism
    ./pirate
    ./podgrab
    ./postgresql
    ./postgresql-backup
    ./prowlarr
    ./pyload
    ./rustdesk
    ./sabnzbd
    ./ssh-server
    ./snapserver
    ./sqlite-backup
    ./syncthing
    ./tandoor-recipes
    ./tlp
    ./transmission
    ./vaultwarden
    ./vikunja
    ./wireguard
    ./woodpecker
  ];
}
