{ ... }: {
  imports = [
    ./adblock
    ./audiobookshelf
    ./backup
    ./backup-server
    ./fail2ban
    ./flood
    ./forgejo
    ./gitea
    ./greetd
    ./grocy
    ./indexers
    ./jellyfin
    ./matrix
    ./mailserver
    ./mealie
    ./meshcentral
    ./miniflux
    ./monitoring
    ./navidrome
    ./nextcloud
    ./nfs
    ./nginx
    ./pirate
    ./podgrab
    ./postgresql
    ./postgresql-backup
    ./pyload
    ./sabnzbd
    ./ssh-server
    ./sqlite-backup
    ./tandoor-recipes
    ./tlp
    ./transmission
    ./vaultwarden
    ./vikunja
    ./wireguard
    ./woodpecker
  ];
}
